version: '3'
services:

  cotoami:
    image: cotoami/cotoami:v0.21.0
    ports:
      - "4000:4000"
    links:
      - redis
      - postgres
      - neo4j
      - maildev
    environment:
      SECRET_KEY_BASE: iirr+1hGL0ew7N/jQmnQ2crnwBBwjHWPkM/QZk7tmD8/ARQhvAH4j69wh1WHH7gv
      COTOAMI_REDIS_HOST: redis
      COTOAMI_REPO_USER: postgres
      COTOAMI_REPO_PASSWORD: postgres
      COTOAMI_REPO_DATABASE: cotoami
      COTOAMI_REPO_HOST: postgres
      COTOAMI_NEO4J_HOST: neo4j
      COTOAMI_SMTP_SERVER: maildev
      COTOAMI_SMTP_PORT: "25"
      COTOAMI_EMAIL_FROM: no-reply@cotoa.me

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:9.5-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cotoami

  neo4j:
    image: neo4j:3.2.2
    ports:
      - "7687:7687"
      - "7474:7474"
    environment:
      NEO4J_AUTH: none

  maildev:
    image: djfarrelly/maildev:latest
    ports:
      - "25:25"
      - "8080:80"